# Generated by Django 2.2.16 on 2020-10-27 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.TextField(choices=[('CUC', 'CUC'), ('CUP', 'CUP'), ('USD', 'USD')], default='USD')),
                ('saldo', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act', models.TextField(choices=[('ing', 'Ingresar'), ('ret', 'Retirar')])),
                ('razon', models.TextField()),
                ('time', models.TimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Account')),
            ],
        ),
    ]
