# Generated by Django 2.2.16 on 2020-10-27 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201027_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='tipo',
            field=models.TextField(choices=[('CUC', 'CUC'), ('CUP', 'CUP'), ('USD', 'USD'), (None, 'Seleccione tipo de moneda')], unique=True),
        ),
    ]
