# Generated by Django 2.2.16 on 2020-10-27 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201027_0112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='time',
            new_name='date',
        ),
    ]
