# Generated by Django 2.2.16 on 2020-10-27 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201027_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
