# Generated by Django 2.2.16 on 2020-10-27 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201027_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='act',
            field=models.TextField(choices=[('1', 'Ingresar'), ('0', 'Retirar'), (None, 'Seleccione acción')]),
        ),
    ]
