# Generated by Django 2.2.16 on 2020-10-27 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201027_0442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='saldo',
            new_name='balance',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='tipo',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='action',
            name='act',
            field=models.TextField(choices=[(1, 'Ingresar'), (0, 'Retirar'), (None, 'Seleccione acción')]),
        ),
    ]
