# Generated by Django 2.2.16 on 2020-10-27 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201027_0532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='razon',
            new_name='reason',
        ),
    ]
